/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"fmt"
)

// CanvasAutoLayoutScope the model 'CanvasAutoLayoutScope'
type CanvasAutoLayoutScope string

// List of CanvasAutoLayoutScope
const (
	CANVASAUTOLAYOUTSCOPE_SCOPE_UNSPECIFIED         CanvasAutoLayoutScope = "SCOPE_UNSPECIFIED"
	CANVASAUTOLAYOUTSCOPE_SCOPE_FULL_CANVAS         CanvasAutoLayoutScope = "SCOPE_FULL_CANVAS"
	CANVASAUTOLAYOUTSCOPE_SCOPE_CONNECTED_COMPONENT CanvasAutoLayoutScope = "SCOPE_CONNECTED_COMPONENT"
	CANVASAUTOLAYOUTSCOPE_SCOPE_EXACT_SET           CanvasAutoLayoutScope = "SCOPE_EXACT_SET"
)

// All allowed values of CanvasAutoLayoutScope enum
var AllowedCanvasAutoLayoutScopeEnumValues = []CanvasAutoLayoutScope{
	"SCOPE_UNSPECIFIED",
	"SCOPE_FULL_CANVAS",
	"SCOPE_CONNECTED_COMPONENT",
	"SCOPE_EXACT_SET",
}

func (v *CanvasAutoLayoutScope) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CanvasAutoLayoutScope(value)
	for _, existing := range AllowedCanvasAutoLayoutScopeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CanvasAutoLayoutScope", value)
}

// NewCanvasAutoLayoutScopeFromValue returns a pointer to a valid CanvasAutoLayoutScope
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCanvasAutoLayoutScopeFromValue(v string) (*CanvasAutoLayoutScope, error) {
	ev := CanvasAutoLayoutScope(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CanvasAutoLayoutScope: valid values are %v", v, AllowedCanvasAutoLayoutScopeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CanvasAutoLayoutScope) IsValid() bool {
	for _, existing := range AllowedCanvasAutoLayoutScopeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CanvasAutoLayoutScope value
func (v CanvasAutoLayoutScope) Ptr() *CanvasAutoLayoutScope {
	return &v
}

type NullableCanvasAutoLayoutScope struct {
	value *CanvasAutoLayoutScope
	isSet bool
}

func (v NullableCanvasAutoLayoutScope) Get() *CanvasAutoLayoutScope {
	return v.value
}

func (v *NullableCanvasAutoLayoutScope) Set(val *CanvasAutoLayoutScope) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasAutoLayoutScope) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasAutoLayoutScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasAutoLayoutScope(val *CanvasAutoLayoutScope) *NullableCanvasAutoLayoutScope {
	return &NullableCanvasAutoLayoutScope{value: val, isSet: true}
}

func (v NullableCanvasAutoLayoutScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasAutoLayoutScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
