/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"fmt"
)

// CanvasAutoLayoutAlgorithm the model 'CanvasAutoLayoutAlgorithm'
type CanvasAutoLayoutAlgorithm string

// List of CanvasAutoLayoutAlgorithm
const (
	CANVASAUTOLAYOUTALGORITHM_ALGORITHM_UNSPECIFIED CanvasAutoLayoutAlgorithm = "ALGORITHM_UNSPECIFIED"
	CANVASAUTOLAYOUTALGORITHM_ALGORITHM_HORIZONTAL  CanvasAutoLayoutAlgorithm = "ALGORITHM_HORIZONTAL"
)

// All allowed values of CanvasAutoLayoutAlgorithm enum
var AllowedCanvasAutoLayoutAlgorithmEnumValues = []CanvasAutoLayoutAlgorithm{
	"ALGORITHM_UNSPECIFIED",
	"ALGORITHM_HORIZONTAL",
}

func (v *CanvasAutoLayoutAlgorithm) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CanvasAutoLayoutAlgorithm(value)
	for _, existing := range AllowedCanvasAutoLayoutAlgorithmEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CanvasAutoLayoutAlgorithm", value)
}

// NewCanvasAutoLayoutAlgorithmFromValue returns a pointer to a valid CanvasAutoLayoutAlgorithm
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCanvasAutoLayoutAlgorithmFromValue(v string) (*CanvasAutoLayoutAlgorithm, error) {
	ev := CanvasAutoLayoutAlgorithm(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CanvasAutoLayoutAlgorithm: valid values are %v", v, AllowedCanvasAutoLayoutAlgorithmEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CanvasAutoLayoutAlgorithm) IsValid() bool {
	for _, existing := range AllowedCanvasAutoLayoutAlgorithmEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CanvasAutoLayoutAlgorithm value
func (v CanvasAutoLayoutAlgorithm) Ptr() *CanvasAutoLayoutAlgorithm {
	return &v
}

type NullableCanvasAutoLayoutAlgorithm struct {
	value *CanvasAutoLayoutAlgorithm
	isSet bool
}

func (v NullableCanvasAutoLayoutAlgorithm) Get() *CanvasAutoLayoutAlgorithm {
	return v.value
}

func (v *NullableCanvasAutoLayoutAlgorithm) Set(val *CanvasAutoLayoutAlgorithm) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasAutoLayoutAlgorithm) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasAutoLayoutAlgorithm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasAutoLayoutAlgorithm(val *CanvasAutoLayoutAlgorithm) *NullableCanvasAutoLayoutAlgorithm {
	return &NullableCanvasAutoLayoutAlgorithm{value: val, isSet: true}
}

func (v NullableCanvasAutoLayoutAlgorithm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasAutoLayoutAlgorithm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
