/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the CanvasesUpdateCanvasBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanvasesUpdateCanvasBody{}

// CanvasesUpdateCanvasBody struct for CanvasesUpdateCanvasBody
type CanvasesUpdateCanvasBody struct {
	Canvas     *CanvasesCanvas           `json:"canvas,omitempty"`
	AutoLayout *CanvasesCanvasAutoLayout `json:"autoLayout,omitempty"`
}

// NewCanvasesUpdateCanvasBody instantiates a new CanvasesUpdateCanvasBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvasesUpdateCanvasBody() *CanvasesUpdateCanvasBody {
	this := CanvasesUpdateCanvasBody{}
	return &this
}

// NewCanvasesUpdateCanvasBodyWithDefaults instantiates a new CanvasesUpdateCanvasBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasesUpdateCanvasBodyWithDefaults() *CanvasesUpdateCanvasBody {
	this := CanvasesUpdateCanvasBody{}
	return &this
}

// GetCanvas returns the Canvas field value if set, zero value otherwise.
func (o *CanvasesUpdateCanvasBody) GetCanvas() CanvasesCanvas {
	if o == nil || IsNil(o.Canvas) {
		var ret CanvasesCanvas
		return ret
	}
	return *o.Canvas
}

// GetCanvasOk returns a tuple with the Canvas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesUpdateCanvasBody) GetCanvasOk() (*CanvasesCanvas, bool) {
	if o == nil || IsNil(o.Canvas) {
		return nil, false
	}
	return o.Canvas, true
}

// HasCanvas returns a boolean if a field has been set.
func (o *CanvasesUpdateCanvasBody) HasCanvas() bool {
	if o != nil && !IsNil(o.Canvas) {
		return true
	}

	return false
}

// SetCanvas gets a reference to the given CanvasesCanvas and assigns it to the Canvas field.
func (o *CanvasesUpdateCanvasBody) SetCanvas(v CanvasesCanvas) {
	o.Canvas = &v
}

// GetAutoLayout returns the AutoLayout field value if set, zero value otherwise.
func (o *CanvasesUpdateCanvasBody) GetAutoLayout() CanvasesCanvasAutoLayout {
	if o == nil || IsNil(o.AutoLayout) {
		var ret CanvasesCanvasAutoLayout
		return ret
	}
	return *o.AutoLayout
}

// GetAutoLayoutOk returns a tuple with the AutoLayout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesUpdateCanvasBody) GetAutoLayoutOk() (*CanvasesCanvasAutoLayout, bool) {
	if o == nil || IsNil(o.AutoLayout) {
		return nil, false
	}
	return o.AutoLayout, true
}

// HasAutoLayout returns a boolean if a field has been set.
func (o *CanvasesUpdateCanvasBody) HasAutoLayout() bool {
	if o != nil && !IsNil(o.AutoLayout) {
		return true
	}

	return false
}

// SetAutoLayout gets a reference to the given CanvasesCanvasAutoLayout and assigns it to the AutoLayout field.
func (o *CanvasesUpdateCanvasBody) SetAutoLayout(v CanvasesCanvasAutoLayout) {
	o.AutoLayout = &v
}

func (o CanvasesUpdateCanvasBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanvasesUpdateCanvasBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Canvas) {
		toSerialize["canvas"] = o.Canvas
	}
	if !IsNil(o.AutoLayout) {
		toSerialize["autoLayout"] = o.AutoLayout
	}
	return toSerialize, nil
}

type NullableCanvasesUpdateCanvasBody struct {
	value *CanvasesUpdateCanvasBody
	isSet bool
}

func (v NullableCanvasesUpdateCanvasBody) Get() *CanvasesUpdateCanvasBody {
	return v.value
}

func (v *NullableCanvasesUpdateCanvasBody) Set(val *CanvasesUpdateCanvasBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasesUpdateCanvasBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasesUpdateCanvasBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasesUpdateCanvasBody(val *CanvasesUpdateCanvasBody) *NullableCanvasesUpdateCanvasBody {
	return &NullableCanvasesUpdateCanvasBody{value: val, isSet: true}
}

func (v NullableCanvasesUpdateCanvasBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasesUpdateCanvasBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
