/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the CanvasesCanvasAutoLayout type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanvasesCanvasAutoLayout{}

// CanvasesCanvasAutoLayout struct for CanvasesCanvasAutoLayout
type CanvasesCanvasAutoLayout struct {
	Algorithm *CanvasAutoLayoutAlgorithm `json:"algorithm,omitempty"`
	NodeIds   []string                   `json:"nodeIds,omitempty"`
	Scope     *CanvasAutoLayoutScope     `json:"scope,omitempty"`
}

// NewCanvasesCanvasAutoLayout instantiates a new CanvasesCanvasAutoLayout object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvasesCanvasAutoLayout() *CanvasesCanvasAutoLayout {
	this := CanvasesCanvasAutoLayout{}
	var algorithm CanvasAutoLayoutAlgorithm = CANVASAUTOLAYOUTALGORITHM_ALGORITHM_UNSPECIFIED
	this.Algorithm = &algorithm
	var scope CanvasAutoLayoutScope = CANVASAUTOLAYOUTSCOPE_SCOPE_UNSPECIFIED
	this.Scope = &scope
	return &this
}

// NewCanvasesCanvasAutoLayoutWithDefaults instantiates a new CanvasesCanvasAutoLayout object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasesCanvasAutoLayoutWithDefaults() *CanvasesCanvasAutoLayout {
	this := CanvasesCanvasAutoLayout{}
	var algorithm CanvasAutoLayoutAlgorithm = CANVASAUTOLAYOUTALGORITHM_ALGORITHM_UNSPECIFIED
	this.Algorithm = &algorithm
	var scope CanvasAutoLayoutScope = CANVASAUTOLAYOUTSCOPE_SCOPE_UNSPECIFIED
	this.Scope = &scope
	return &this
}

// GetAlgorithm returns the Algorithm field value if set, zero value otherwise.
func (o *CanvasesCanvasAutoLayout) GetAlgorithm() CanvasAutoLayoutAlgorithm {
	if o == nil || IsNil(o.Algorithm) {
		var ret CanvasAutoLayoutAlgorithm
		return ret
	}
	return *o.Algorithm
}

// GetAlgorithmOk returns a tuple with the Algorithm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasAutoLayout) GetAlgorithmOk() (*CanvasAutoLayoutAlgorithm, bool) {
	if o == nil || IsNil(o.Algorithm) {
		return nil, false
	}
	return o.Algorithm, true
}

// HasAlgorithm returns a boolean if a field has been set.
func (o *CanvasesCanvasAutoLayout) HasAlgorithm() bool {
	if o != nil && !IsNil(o.Algorithm) {
		return true
	}

	return false
}

// SetAlgorithm gets a reference to the given CanvasAutoLayoutAlgorithm and assigns it to the Algorithm field.
func (o *CanvasesCanvasAutoLayout) SetAlgorithm(v CanvasAutoLayoutAlgorithm) {
	o.Algorithm = &v
}

// GetNodeIds returns the NodeIds field value if set, zero value otherwise.
func (o *CanvasesCanvasAutoLayout) GetNodeIds() []string {
	if o == nil || IsNil(o.NodeIds) {
		var ret []string
		return ret
	}
	return o.NodeIds
}

// GetNodeIdsOk returns a tuple with the NodeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasAutoLayout) GetNodeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.NodeIds) {
		return nil, false
	}
	return o.NodeIds, true
}

// HasNodeIds returns a boolean if a field has been set.
func (o *CanvasesCanvasAutoLayout) HasNodeIds() bool {
	if o != nil && !IsNil(o.NodeIds) {
		return true
	}

	return false
}

// SetNodeIds gets a reference to the given []string and assigns it to the NodeIds field.
func (o *CanvasesCanvasAutoLayout) SetNodeIds(v []string) {
	o.NodeIds = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *CanvasesCanvasAutoLayout) GetScope() CanvasAutoLayoutScope {
	if o == nil || IsNil(o.Scope) {
		var ret CanvasAutoLayoutScope
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasAutoLayout) GetScopeOk() (*CanvasAutoLayoutScope, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *CanvasesCanvasAutoLayout) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given CanvasAutoLayoutScope and assigns it to the Scope field.
func (o *CanvasesCanvasAutoLayout) SetScope(v CanvasAutoLayoutScope) {
	o.Scope = &v
}

func (o CanvasesCanvasAutoLayout) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanvasesCanvasAutoLayout) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Algorithm) {
		toSerialize["algorithm"] = o.Algorithm
	}
	if !IsNil(o.NodeIds) {
		toSerialize["nodeIds"] = o.NodeIds
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

type NullableCanvasesCanvasAutoLayout struct {
	value *CanvasesCanvasAutoLayout
	isSet bool
}

func (v NullableCanvasesCanvasAutoLayout) Get() *CanvasesCanvasAutoLayout {
	return v.value
}

func (v *NullableCanvasesCanvasAutoLayout) Set(val *CanvasesCanvasAutoLayout) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasesCanvasAutoLayout) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasesCanvasAutoLayout) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasesCanvasAutoLayout(val *CanvasesCanvasAutoLayout) *NullableCanvasesCanvasAutoLayout {
	return &NullableCanvasesCanvasAutoLayout{value: val, isSet: true}
}

func (v NullableCanvasesCanvasAutoLayout) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasesCanvasAutoLayout) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
