// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: configuration.proto

package configuration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Field struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required             bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue         *string                `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Label                string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	VisibilityConditions []*VisibilityCondition `protobuf:"bytes,7,rep,name=visibility_conditions,json=visibilityConditions,proto3" json:"visibility_conditions,omitempty"`
	TypeOptions          *TypeOptions           `protobuf:"bytes,8,opt,name=type_options,json=typeOptions,proto3,oneof" json:"type_options,omitempty"`
	RequiredConditions   []*RequiredCondition   `protobuf:"bytes,9,rep,name=required_conditions,json=requiredConditions,proto3" json:"required_conditions,omitempty"`
	ValidationRules      []*ValidationRule      `protobuf:"bytes,10,rep,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	Placeholder          *string                `protobuf:"bytes,11,opt,name=placeholder,proto3,oneof" json:"placeholder,omitempty"`
	Sensitive            *bool                  `protobuf:"varint,12,opt,name=sensitive,proto3,oneof" json:"sensitive,omitempty"`
	Togglable            *bool                  `protobuf:"varint,13,opt,name=togglable,proto3,oneof" json:"togglable,omitempty"`
	DisallowExpression   *bool                  `protobuf:"varint,14,opt,name=disallow_expression,json=disallowExpression,proto3,oneof" json:"disallow_expression,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Field) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Field) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *Field) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Field) GetVisibilityConditions() []*VisibilityCondition {
	if x != nil {
		return x.VisibilityConditions
	}
	return nil
}

func (x *Field) GetTypeOptions() *TypeOptions {
	if x != nil {
		return x.TypeOptions
	}
	return nil
}

func (x *Field) GetRequiredConditions() []*RequiredCondition {
	if x != nil {
		return x.RequiredConditions
	}
	return nil
}

func (x *Field) GetValidationRules() []*ValidationRule {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

func (x *Field) GetPlaceholder() string {
	if x != nil && x.Placeholder != nil {
		return *x.Placeholder
	}
	return ""
}

func (x *Field) GetSensitive() bool {
	if x != nil && x.Sensitive != nil {
		return *x.Sensitive
	}
	return false
}

func (x *Field) GetTogglable() bool {
	if x != nil && x.Togglable != nil {
		return *x.Togglable
	}
	return false
}

func (x *Field) GetDisallowExpression() bool {
	if x != nil && x.DisallowExpression != nil {
		return *x.DisallowExpression
	}
	return false
}

type TypeOptions struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Number           *NumberTypeOptions           `protobuf:"bytes,1,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Select           *SelectTypeOptions           `protobuf:"bytes,2,opt,name=select,proto3,oneof" json:"select,omitempty"`
	MultiSelect      *MultiSelectTypeOptions      `protobuf:"bytes,3,opt,name=multi_select,json=multiSelect,proto3,oneof" json:"multi_select,omitempty"`
	List             *ListTypeOptions             `protobuf:"bytes,4,opt,name=list,proto3,oneof" json:"list,omitempty"`
	Object           *ObjectTypeOptions           `protobuf:"bytes,5,opt,name=object,proto3,oneof" json:"object,omitempty"`
	Resource         *ResourceTypeOptions         `protobuf:"bytes,6,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	Time             *TimeTypeOptions             `protobuf:"bytes,7,opt,name=time,proto3,oneof" json:"time,omitempty"`
	Date             *DateTypeOptions             `protobuf:"bytes,8,opt,name=date,proto3,oneof" json:"date,omitempty"`
	Datetime         *DateTimeTypeOptions         `protobuf:"bytes,9,opt,name=datetime,proto3,oneof" json:"datetime,omitempty"`
	AnyPredicateList *AnyPredicateListTypeOptions `protobuf:"bytes,10,opt,name=any_predicate_list,json=anyPredicateList,proto3,oneof" json:"any_predicate_list,omitempty"`
	String_          *StringTypeOptions           `protobuf:"bytes,11,opt,name=string,proto3,oneof" json:"string,omitempty"`
	Expression       *ExpressionTypeOptions       `protobuf:"bytes,12,opt,name=expression,proto3,oneof" json:"expression,omitempty"`
	Text             *TextTypeOptions             `protobuf:"bytes,13,opt,name=text,proto3,oneof" json:"text,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TypeOptions) Reset() {
	*x = TypeOptions{}
	mi := &file_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeOptions) ProtoMessage() {}

func (x *TypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeOptions.ProtoReflect.Descriptor instead.
func (*TypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *TypeOptions) GetNumber() *NumberTypeOptions {
	if x != nil {
		return x.Number
	}
	return nil
}

func (x *TypeOptions) GetSelect() *SelectTypeOptions {
	if x != nil {
		return x.Select
	}
	return nil
}

func (x *TypeOptions) GetMultiSelect() *MultiSelectTypeOptions {
	if x != nil {
		return x.MultiSelect
	}
	return nil
}

func (x *TypeOptions) GetList() *ListTypeOptions {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *TypeOptions) GetObject() *ObjectTypeOptions {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *TypeOptions) GetResource() *ResourceTypeOptions {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *TypeOptions) GetTime() *TimeTypeOptions {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *TypeOptions) GetDate() *DateTypeOptions {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *TypeOptions) GetDatetime() *DateTimeTypeOptions {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *TypeOptions) GetAnyPredicateList() *AnyPredicateListTypeOptions {
	if x != nil {
		return x.AnyPredicateList
	}
	return nil
}

func (x *TypeOptions) GetString_() *StringTypeOptions {
	if x != nil {
		return x.String_
	}
	return nil
}

func (x *TypeOptions) GetExpression() *ExpressionTypeOptions {
	if x != nil {
		return x.Expression
	}
	return nil
}

func (x *TypeOptions) GetText() *TextTypeOptions {
	if x != nil {
		return x.Text
	}
	return nil
}

type NumberTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *int32                 `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *int32                 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberTypeOptions) Reset() {
	*x = NumberTypeOptions{}
	mi := &file_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberTypeOptions) ProtoMessage() {}

func (x *NumberTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberTypeOptions.ProtoReflect.Descriptor instead.
func (*NumberTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *NumberTypeOptions) GetMin() int32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *NumberTypeOptions) GetMax() int32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type StringTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLength     *int32                 `protobuf:"varint,1,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTypeOptions) Reset() {
	*x = StringTypeOptions{}
	mi := &file_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTypeOptions) ProtoMessage() {}

func (x *StringTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTypeOptions.ProtoReflect.Descriptor instead.
func (*StringTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *StringTypeOptions) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *StringTypeOptions) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

type ExpressionTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLength     *int32                 `protobuf:"varint,1,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionTypeOptions) Reset() {
	*x = ExpressionTypeOptions{}
	mi := &file_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionTypeOptions) ProtoMessage() {}

func (x *ExpressionTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionTypeOptions.ProtoReflect.Descriptor instead.
func (*ExpressionTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *ExpressionTypeOptions) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *ExpressionTypeOptions) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

type TextTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLength     *int32                 `protobuf:"varint,1,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextTypeOptions) Reset() {
	*x = TextTypeOptions{}
	mi := &file_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextTypeOptions) ProtoMessage() {}

func (x *TextTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextTypeOptions.ProtoReflect.Descriptor instead.
func (*TextTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{5}
}

func (x *TextTypeOptions) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *TextTypeOptions) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

type TimeTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *string                `protobuf:"bytes,1,opt,name=format,proto3,oneof" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeTypeOptions) Reset() {
	*x = TimeTypeOptions{}
	mi := &file_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeTypeOptions) ProtoMessage() {}

func (x *TimeTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeTypeOptions.ProtoReflect.Descriptor instead.
func (*TimeTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{6}
}

func (x *TimeTypeOptions) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

type DateTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *string                `protobuf:"bytes,1,opt,name=format,proto3,oneof" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateTypeOptions) Reset() {
	*x = DateTypeOptions{}
	mi := &file_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTypeOptions) ProtoMessage() {}

func (x *DateTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTypeOptions.ProtoReflect.Descriptor instead.
func (*DateTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{7}
}

func (x *DateTypeOptions) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

type DateTimeTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *string                `protobuf:"bytes,1,opt,name=format,proto3,oneof" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateTimeTypeOptions) Reset() {
	*x = DateTimeTypeOptions{}
	mi := &file_configuration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTimeTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTimeTypeOptions) ProtoMessage() {}

func (x *DateTimeTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTimeTypeOptions.ProtoReflect.Descriptor instead.
func (*DateTimeTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{8}
}

func (x *DateTimeTypeOptions) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

type SelectTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*SelectOption        `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectTypeOptions) Reset() {
	*x = SelectTypeOptions{}
	mi := &file_configuration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectTypeOptions) ProtoMessage() {}

func (x *SelectTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectTypeOptions.ProtoReflect.Descriptor instead.
func (*SelectTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{9}
}

func (x *SelectTypeOptions) GetOptions() []*SelectOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type MultiSelectTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*SelectOption        `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiSelectTypeOptions) Reset() {
	*x = MultiSelectTypeOptions{}
	mi := &file_configuration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSelectTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSelectTypeOptions) ProtoMessage() {}

func (x *MultiSelectTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSelectTypeOptions.ProtoReflect.Descriptor instead.
func (*MultiSelectTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{10}
}

func (x *MultiSelectTypeOptions) GetOptions() []*SelectOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ResourceTypeOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	UseNameAsValue bool                   `protobuf:"varint,2,opt,name=use_name_as_value,json=useNameAsValue,proto3" json:"use_name_as_value,omitempty"`
	Multi          bool                   `protobuf:"varint,3,opt,name=multi,proto3" json:"multi,omitempty"`
	Parameters     []*ParameterRef        `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceTypeOptions) Reset() {
	*x = ResourceTypeOptions{}
	mi := &file_configuration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTypeOptions) ProtoMessage() {}

func (x *ResourceTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTypeOptions.ProtoReflect.Descriptor instead.
func (*ResourceTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceTypeOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceTypeOptions) GetUseNameAsValue() bool {
	if x != nil {
		return x.UseNameAsValue
	}
	return false
}

func (x *ResourceTypeOptions) GetMulti() bool {
	if x != nil {
		return x.Multi
	}
	return false
}

func (x *ResourceTypeOptions) GetParameters() []*ParameterRef {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ParameterRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueFrom     *ParameterValueFrom    `protobuf:"bytes,3,opt,name=value_from,json=valueFrom,proto3" json:"value_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterRef) Reset() {
	*x = ParameterRef{}
	mi := &file_configuration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterRef) ProtoMessage() {}

func (x *ParameterRef) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterRef.ProtoReflect.Descriptor instead.
func (*ParameterRef) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{12}
}

func (x *ParameterRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterRef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ParameterRef) GetValueFrom() *ParameterValueFrom {
	if x != nil {
		return x.ValueFrom
	}
	return nil
}

type ParameterValueFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterValueFrom) Reset() {
	*x = ParameterValueFrom{}
	mi := &file_configuration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterValueFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterValueFrom) ProtoMessage() {}

func (x *ParameterValueFrom) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterValueFrom.ProtoReflect.Descriptor instead.
func (*ParameterValueFrom) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{13}
}

func (x *ParameterValueFrom) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type ListTypeOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemDefinition *ListItemDefinition    `protobuf:"bytes,1,opt,name=item_definition,json=itemDefinition,proto3" json:"item_definition,omitempty"`
	ItemLabel      string                 `protobuf:"bytes,2,opt,name=item_label,json=itemLabel,proto3" json:"item_label,omitempty"`
	MaxItems       *int32                 `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3,oneof" json:"max_items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTypeOptions) Reset() {
	*x = ListTypeOptions{}
	mi := &file_configuration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypeOptions) ProtoMessage() {}

func (x *ListTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypeOptions.ProtoReflect.Descriptor instead.
func (*ListTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{14}
}

func (x *ListTypeOptions) GetItemDefinition() *ListItemDefinition {
	if x != nil {
		return x.ItemDefinition
	}
	return nil
}

func (x *ListTypeOptions) GetItemLabel() string {
	if x != nil {
		return x.ItemLabel
	}
	return ""
}

func (x *ListTypeOptions) GetMaxItems() int32 {
	if x != nil && x.MaxItems != nil {
		return *x.MaxItems
	}
	return 0
}

type ObjectTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        []*Field               `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectTypeOptions) Reset() {
	*x = ObjectTypeOptions{}
	mi := &file_configuration_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectTypeOptions) ProtoMessage() {}

func (x *ObjectTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectTypeOptions.ProtoReflect.Descriptor instead.
func (*ObjectTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{15}
}

func (x *ObjectTypeOptions) GetSchema() []*Field {
	if x != nil {
		return x.Schema
	}
	return nil
}

type SelectOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOption) Reset() {
	*x = SelectOption{}
	mi := &file_configuration_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOption) ProtoMessage() {}

func (x *SelectOption) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOption.ProtoReflect.Descriptor instead.
func (*SelectOption) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{16}
}

func (x *SelectOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SelectOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VisibilityCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityCondition) Reset() {
	*x = VisibilityCondition{}
	mi := &file_configuration_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityCondition) ProtoMessage() {}

func (x *VisibilityCondition) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityCondition.ProtoReflect.Descriptor instead.
func (*VisibilityCondition) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{17}
}

func (x *VisibilityCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *VisibilityCondition) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ListItemDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Schema        []*Field               `protobuf:"bytes,2,rep,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemDefinition) Reset() {
	*x = ListItemDefinition{}
	mi := &file_configuration_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemDefinition) ProtoMessage() {}

func (x *ListItemDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemDefinition.ProtoReflect.Descriptor instead.
func (*ListItemDefinition) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{18}
}

func (x *ListItemDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListItemDefinition) GetSchema() []*Field {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RequiredCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredCondition) Reset() {
	*x = RequiredCondition{}
	mi := &file_configuration_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredCondition) ProtoMessage() {}

func (x *RequiredCondition) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredCondition.ProtoReflect.Descriptor instead.
func (*RequiredCondition) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{19}
}

func (x *RequiredCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RequiredCondition) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ValidationRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CompareWith   string                 `protobuf:"bytes,2,opt,name=compare_with,json=compareWith,proto3" json:"compare_with,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationRule) Reset() {
	*x = ValidationRule{}
	mi := &file_configuration_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRule) ProtoMessage() {}

func (x *ValidationRule) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRule.ProtoReflect.Descriptor instead.
func (*ValidationRule) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{20}
}

func (x *ValidationRule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ValidationRule) GetCompareWith() string {
	if x != nil {
		return x.CompareWith
	}
	return ""
}

func (x *ValidationRule) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type AnyPredicateListTypeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operators     []*SelectOption        `protobuf:"bytes,1,rep,name=operators,proto3" json:"operators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyPredicateListTypeOptions) Reset() {
	*x = AnyPredicateListTypeOptions{}
	mi := &file_configuration_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyPredicateListTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyPredicateListTypeOptions) ProtoMessage() {}

func (x *AnyPredicateListTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyPredicateListTypeOptions.ProtoReflect.Descriptor instead.
func (*AnyPredicateListTypeOptions) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{21}
}

func (x *AnyPredicateListTypeOptions) GetOperators() []*SelectOption {
	if x != nil {
		return x.Operators
	}
	return nil
}

var File_configuration_proto protoreflect.FileDescriptor

const file_configuration_proto_rawDesc = "" +
	"\n" +
	"\x13configuration.proto\x12\x18Superplane.Configuration\"\x9d\x06\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12(\n" +
	"\rdefault_value\x18\x05 \x01(\tH\x00R\fdefaultValue\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12b\n" +
	"\x15visibility_conditions\x18\a \x03(\v2-.Superplane.Configuration.VisibilityConditionR\x14visibilityConditions\x12M\n" +
	"\ftype_options\x18\b \x01(\v2%.Superplane.Configuration.TypeOptionsH\x01R\vtypeOptions\x88\x01\x01\x12\\\n" +
	"\x13required_conditions\x18\t \x03(\v2+.Superplane.Configuration.RequiredConditionR\x12requiredConditions\x12S\n" +
	"\x10validation_rules\x18\n" +
	" \x03(\v2(.Superplane.Configuration.ValidationRuleR\x0fvalidationRules\x12%\n" +
	"\vplaceholder\x18\v \x01(\tH\x02R\vplaceholder\x88\x01\x01\x12!\n" +
	"\tsensitive\x18\f \x01(\bH\x03R\tsensitive\x88\x01\x01\x12!\n" +
	"\ttogglable\x18\r \x01(\bH\x04R\ttogglable\x88\x01\x01\x124\n" +
	"\x13disallow_expression\x18\x0e \x01(\bH\x05R\x12disallowExpression\x88\x01\x01B\x10\n" +
	"\x0e_default_valueB\x0f\n" +
	"\r_type_optionsB\x0e\n" +
	"\f_placeholderB\f\n" +
	"\n" +
	"_sensitiveB\f\n" +
	"\n" +
	"_togglableB\x16\n" +
	"\x14_disallow_expression\"\xa0\t\n" +
	"\vTypeOptions\x12H\n" +
	"\x06number\x18\x01 \x01(\v2+.Superplane.Configuration.NumberTypeOptionsH\x00R\x06number\x88\x01\x01\x12H\n" +
	"\x06select\x18\x02 \x01(\v2+.Superplane.Configuration.SelectTypeOptionsH\x01R\x06select\x88\x01\x01\x12X\n" +
	"\fmulti_select\x18\x03 \x01(\v20.Superplane.Configuration.MultiSelectTypeOptionsH\x02R\vmultiSelect\x88\x01\x01\x12B\n" +
	"\x04list\x18\x04 \x01(\v2).Superplane.Configuration.ListTypeOptionsH\x03R\x04list\x88\x01\x01\x12H\n" +
	"\x06object\x18\x05 \x01(\v2+.Superplane.Configuration.ObjectTypeOptionsH\x04R\x06object\x88\x01\x01\x12N\n" +
	"\bresource\x18\x06 \x01(\v2-.Superplane.Configuration.ResourceTypeOptionsH\x05R\bresource\x88\x01\x01\x12B\n" +
	"\x04time\x18\a \x01(\v2).Superplane.Configuration.TimeTypeOptionsH\x06R\x04time\x88\x01\x01\x12B\n" +
	"\x04date\x18\b \x01(\v2).Superplane.Configuration.DateTypeOptionsH\aR\x04date\x88\x01\x01\x12N\n" +
	"\bdatetime\x18\t \x01(\v2-.Superplane.Configuration.DateTimeTypeOptionsH\bR\bdatetime\x88\x01\x01\x12h\n" +
	"\x12any_predicate_list\x18\n" +
	" \x01(\v25.Superplane.Configuration.AnyPredicateListTypeOptionsH\tR\x10anyPredicateList\x88\x01\x01\x12H\n" +
	"\x06string\x18\v \x01(\v2+.Superplane.Configuration.StringTypeOptionsH\n" +
	"R\x06string\x88\x01\x01\x12T\n" +
	"\n" +
	"expression\x18\f \x01(\v2/.Superplane.Configuration.ExpressionTypeOptionsH\vR\n" +
	"expression\x88\x01\x01\x12B\n" +
	"\x04text\x18\r \x01(\v2).Superplane.Configuration.TextTypeOptionsH\fR\x04text\x88\x01\x01B\t\n" +
	"\a_numberB\t\n" +
	"\a_selectB\x0f\n" +
	"\r_multi_selectB\a\n" +
	"\x05_listB\t\n" +
	"\a_objectB\v\n" +
	"\t_resourceB\a\n" +
	"\x05_timeB\a\n" +
	"\x05_dateB\v\n" +
	"\t_datetimeB\x15\n" +
	"\x13_any_predicate_listB\t\n" +
	"\a_stringB\r\n" +
	"\v_expressionB\a\n" +
	"\x05_text\"Q\n" +
	"\x11NumberTypeOptions\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x05H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x05H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"y\n" +
	"\x11StringTypeOptions\x12\"\n" +
	"\n" +
	"min_length\x18\x01 \x01(\x05H\x00R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x02 \x01(\x05H\x01R\tmaxLength\x88\x01\x01B\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_length\"}\n" +
	"\x15ExpressionTypeOptions\x12\"\n" +
	"\n" +
	"min_length\x18\x01 \x01(\x05H\x00R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x02 \x01(\x05H\x01R\tmaxLength\x88\x01\x01B\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_length\"w\n" +
	"\x0fTextTypeOptions\x12\"\n" +
	"\n" +
	"min_length\x18\x01 \x01(\x05H\x00R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x02 \x01(\x05H\x01R\tmaxLength\x88\x01\x01B\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_length\"9\n" +
	"\x0fTimeTypeOptions\x12\x1b\n" +
	"\x06format\x18\x01 \x01(\tH\x00R\x06format\x88\x01\x01B\t\n" +
	"\a_format\"9\n" +
	"\x0fDateTypeOptions\x12\x1b\n" +
	"\x06format\x18\x01 \x01(\tH\x00R\x06format\x88\x01\x01B\t\n" +
	"\a_format\"=\n" +
	"\x13DateTimeTypeOptions\x12\x1b\n" +
	"\x06format\x18\x01 \x01(\tH\x00R\x06format\x88\x01\x01B\t\n" +
	"\a_format\"U\n" +
	"\x11SelectTypeOptions\x12@\n" +
	"\aoptions\x18\x01 \x03(\v2&.Superplane.Configuration.SelectOptionR\aoptions\"Z\n" +
	"\x16MultiSelectTypeOptions\x12@\n" +
	"\aoptions\x18\x01 \x03(\v2&.Superplane.Configuration.SelectOptionR\aoptions\"\xb2\x01\n" +
	"\x13ResourceTypeOptions\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12)\n" +
	"\x11use_name_as_value\x18\x02 \x01(\bR\x0euseNameAsValue\x12\x14\n" +
	"\x05multi\x18\x03 \x01(\bR\x05multi\x12F\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2&.Superplane.Configuration.ParameterRefR\n" +
	"parameters\"\x85\x01\n" +
	"\fParameterRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12K\n" +
	"\n" +
	"value_from\x18\x03 \x01(\v2,.Superplane.Configuration.ParameterValueFromR\tvalueFrom\"*\n" +
	"\x12ParameterValueFrom\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\"\xb7\x01\n" +
	"\x0fListTypeOptions\x12U\n" +
	"\x0fitem_definition\x18\x01 \x01(\v2,.Superplane.Configuration.ListItemDefinitionR\x0eitemDefinition\x12\x1d\n" +
	"\n" +
	"item_label\x18\x02 \x01(\tR\titemLabel\x12 \n" +
	"\tmax_items\x18\x03 \x01(\x05H\x00R\bmaxItems\x88\x01\x01B\f\n" +
	"\n" +
	"_max_items\"L\n" +
	"\x11ObjectTypeOptions\x127\n" +
	"\x06schema\x18\x01 \x03(\v2\x1f.Superplane.Configuration.FieldR\x06schema\":\n" +
	"\fSelectOption\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"C\n" +
	"\x13VisibilityCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"a\n" +
	"\x12ListItemDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x127\n" +
	"\x06schema\x18\x02 \x03(\v2\x1f.Superplane.Configuration.FieldR\x06schema\"A\n" +
	"\x11RequiredCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"r\n" +
	"\x0eValidationRule\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fcompare_with\x18\x02 \x01(\tR\vcompareWith\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"c\n" +
	"\x1bAnyPredicateListTypeOptions\x12D\n" +
	"\toperators\x18\x01 \x03(\v2&.Superplane.Configuration.SelectOptionR\toperatorsB=Z;github.com/superplanehq/superplane/pkg/protos/configurationb\x06proto3"

var (
	file_configuration_proto_rawDescOnce sync.Once
	file_configuration_proto_rawDescData []byte
)

func file_configuration_proto_rawDescGZIP() []byte {
	file_configuration_proto_rawDescOnce.Do(func() {
		file_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)))
	})
	return file_configuration_proto_rawDescData
}

var file_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_configuration_proto_goTypes = []any{
	(*Field)(nil),                       // 0: Superplane.Configuration.Field
	(*TypeOptions)(nil),                 // 1: Superplane.Configuration.TypeOptions
	(*NumberTypeOptions)(nil),           // 2: Superplane.Configuration.NumberTypeOptions
	(*StringTypeOptions)(nil),           // 3: Superplane.Configuration.StringTypeOptions
	(*ExpressionTypeOptions)(nil),       // 4: Superplane.Configuration.ExpressionTypeOptions
	(*TextTypeOptions)(nil),             // 5: Superplane.Configuration.TextTypeOptions
	(*TimeTypeOptions)(nil),             // 6: Superplane.Configuration.TimeTypeOptions
	(*DateTypeOptions)(nil),             // 7: Superplane.Configuration.DateTypeOptions
	(*DateTimeTypeOptions)(nil),         // 8: Superplane.Configuration.DateTimeTypeOptions
	(*SelectTypeOptions)(nil),           // 9: Superplane.Configuration.SelectTypeOptions
	(*MultiSelectTypeOptions)(nil),      // 10: Superplane.Configuration.MultiSelectTypeOptions
	(*ResourceTypeOptions)(nil),         // 11: Superplane.Configuration.ResourceTypeOptions
	(*ParameterRef)(nil),                // 12: Superplane.Configuration.ParameterRef
	(*ParameterValueFrom)(nil),          // 13: Superplane.Configuration.ParameterValueFrom
	(*ListTypeOptions)(nil),             // 14: Superplane.Configuration.ListTypeOptions
	(*ObjectTypeOptions)(nil),           // 15: Superplane.Configuration.ObjectTypeOptions
	(*SelectOption)(nil),                // 16: Superplane.Configuration.SelectOption
	(*VisibilityCondition)(nil),         // 17: Superplane.Configuration.VisibilityCondition
	(*ListItemDefinition)(nil),          // 18: Superplane.Configuration.ListItemDefinition
	(*RequiredCondition)(nil),           // 19: Superplane.Configuration.RequiredCondition
	(*ValidationRule)(nil),              // 20: Superplane.Configuration.ValidationRule
	(*AnyPredicateListTypeOptions)(nil), // 21: Superplane.Configuration.AnyPredicateListTypeOptions
}
var file_configuration_proto_depIdxs = []int32{
	17, // 0: Superplane.Configuration.Field.visibility_conditions:type_name -> Superplane.Configuration.VisibilityCondition
	1,  // 1: Superplane.Configuration.Field.type_options:type_name -> Superplane.Configuration.TypeOptions
	19, // 2: Superplane.Configuration.Field.required_conditions:type_name -> Superplane.Configuration.RequiredCondition
	20, // 3: Superplane.Configuration.Field.validation_rules:type_name -> Superplane.Configuration.ValidationRule
	2,  // 4: Superplane.Configuration.TypeOptions.number:type_name -> Superplane.Configuration.NumberTypeOptions
	9,  // 5: Superplane.Configuration.TypeOptions.select:type_name -> Superplane.Configuration.SelectTypeOptions
	10, // 6: Superplane.Configuration.TypeOptions.multi_select:type_name -> Superplane.Configuration.MultiSelectTypeOptions
	14, // 7: Superplane.Configuration.TypeOptions.list:type_name -> Superplane.Configuration.ListTypeOptions
	15, // 8: Superplane.Configuration.TypeOptions.object:type_name -> Superplane.Configuration.ObjectTypeOptions
	11, // 9: Superplane.Configuration.TypeOptions.resource:type_name -> Superplane.Configuration.ResourceTypeOptions
	6,  // 10: Superplane.Configuration.TypeOptions.time:type_name -> Superplane.Configuration.TimeTypeOptions
	7,  // 11: Superplane.Configuration.TypeOptions.date:type_name -> Superplane.Configuration.DateTypeOptions
	8,  // 12: Superplane.Configuration.TypeOptions.datetime:type_name -> Superplane.Configuration.DateTimeTypeOptions
	21, // 13: Superplane.Configuration.TypeOptions.any_predicate_list:type_name -> Superplane.Configuration.AnyPredicateListTypeOptions
	3,  // 14: Superplane.Configuration.TypeOptions.string:type_name -> Superplane.Configuration.StringTypeOptions
	4,  // 15: Superplane.Configuration.TypeOptions.expression:type_name -> Superplane.Configuration.ExpressionTypeOptions
	5,  // 16: Superplane.Configuration.TypeOptions.text:type_name -> Superplane.Configuration.TextTypeOptions
	16, // 17: Superplane.Configuration.SelectTypeOptions.options:type_name -> Superplane.Configuration.SelectOption
	16, // 18: Superplane.Configuration.MultiSelectTypeOptions.options:type_name -> Superplane.Configuration.SelectOption
	12, // 19: Superplane.Configuration.ResourceTypeOptions.parameters:type_name -> Superplane.Configuration.ParameterRef
	13, // 20: Superplane.Configuration.ParameterRef.value_from:type_name -> Superplane.Configuration.ParameterValueFrom
	18, // 21: Superplane.Configuration.ListTypeOptions.item_definition:type_name -> Superplane.Configuration.ListItemDefinition
	0,  // 22: Superplane.Configuration.ObjectTypeOptions.schema:type_name -> Superplane.Configuration.Field
	0,  // 23: Superplane.Configuration.ListItemDefinition.schema:type_name -> Superplane.Configuration.Field
	16, // 24: Superplane.Configuration.AnyPredicateListTypeOptions.operators:type_name -> Superplane.Configuration.SelectOption
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_configuration_proto_init() }
func file_configuration_proto_init() {
	if File_configuration_proto != nil {
		return
	}
	file_configuration_proto_msgTypes[0].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[1].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[2].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[3].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[4].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[5].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[6].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[7].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[8].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[14].OneofWrappers = []any{}
	file_configuration_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configuration_proto_goTypes,
		DependencyIndexes: file_configuration_proto_depIdxs,
		MessageInfos:      file_configuration_proto_msgTypes,
	}.Build()
	File_configuration_proto = out.File
	file_configuration_proto_goTypes = nil
	file_configuration_proto_depIdxs = nil
}
